kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: redditopenttd/ottdstats
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
